### PR TITLE
Feature/cal 3

### PR DESCRIPTION
**Pull request by JegoRamos**
# We finished the subtract feature. Please scrutinize our code because my programming partner keeps playing frozen songs in the background.

### CODE REVIEW

**Comment by JegoRamos** [comment]
Wait, there was a bug in production. We need to patch a hotfix first.

**Comment by JegoRamos** [comment]
Does this mean we have to pull in the hotfix that can potentially conflict our code?

**Comment by JegoRamos** [comment]
Yes, and judging by your pull request. The patch will be made at the same files you've worked with. Expect major conflicts. :(

**Comment by JegoRamos** [comment]
OMG. I don't want to work with this company anymore. This happens all the time!

**Comment by JegoRamos** [comment]
Listen, you little piece of peanut butter, I'll let you refactor the patch if you agree to cascade it to your feature. Okay?

**Comment by JegoRamos** [comment]
And give me a 30% increase and a 1 month bonus

**Comment by JegoRamos** [comment]
Fine. Now, go watch some HBO or something.

**Comment by ron-blackpearl** [comment]
Wait for Hotfix to be merged to Prod.

**Comment by ron-blackpearl** [comment]
Production branch is updated with hotfix CAL-4. Please update your branches

**Pull request merged**
